name = "backend-medium"
compatibility_date = "2025-01-02"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzNhNTQwNDAtMmRjMC00YmUzLTk4NmQtOTk4NDkxMTkxNmRkIiwidGVuYW50X2lkIjoiNDc4NTc4MWQ3ZTM2MzMyOTVkNzE1ZWFlNzBmNDJmMzk5NDQ5MmU3MzNiNjZmMDEzMjVhMTc1MjgxNjZmZTMzNCIsImludGVybmFsX3NlY3JldCI6Ijg0NGI1MzViLTczNDQtNGViNC04ZDNiLWQ0NzBiMjEyZmVjZiJ9.3aaZxo3sio3f2m0SlMljPOxZb_psCY4R6c6LEy1pOSU"
JWT_SECRET = "Vishal1secret"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
